### PR TITLE
MongoDB Implementation

### PR DESCRIPTION
**Pull request by poying**

### CODE REVIEW

**Comment by yehohanan7** [comment]
Hi @poying, could you please add the dependencies to vendor/manifest? just do a gvt fetch for all the dependencies.

**Comment by poying** [comment]
@yehohanan7 Sory I forgot to do that. :stuck_out_tongue:

**Comment by yehohanan7** [comment]
@poying i merged the changes, would be nice if you could also add a simple example section specific to mongodb on the README page.

**Comment by poying** [comment]
@yehohanan7 Sure, I will do it today.

**Pull request merged**
